//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFishShop.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OnlineFishShopResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnlineFishShopResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineFishShop.Common.Resources.OnlineFishShopResources", typeof(OnlineFishShopResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влезте в профила си.
        /// </summary>
        public static string lblAccountLogin {
            get {
                return ResourceManager.GetString("lblAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Административен панел.
        /// </summary>
        public static string lblAdminPanel {
            get {
                return ResourceManager.GetString("lblAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        public static string lblBlog {
            get {
                return ResourceManager.GetString("lblBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждаване на парола.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string lblContatcs {
            get {
                return ResourceManager.GetString("lblContatcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright - 2019.
        /// </summary>
        public static string lblCopyright {
            get {
                return ResourceManager.GetString("lblCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на нов потребител.
        /// </summary>
        public static string lblCreateNewAccount {
            get {
                return ResourceManager.GetString("lblCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еmail адрес.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола?.
        /// </summary>
        public static string lblForgotPassword {
            get {
                return ResourceManager.GetString("lblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте,.
        /// </summary>
        public static string lblHello {
            get {
                return ResourceManager.GetString("lblHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукти.
        /// </summary>
        public static string lblProducts {
            get {
                return ResourceManager.GetString("lblProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string lblRegister {
            get {
                return ResourceManager.GetString("lblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистриране на нов потребител.
        /// </summary>
        public static string lblRegisterNew {
            get {
                return ResourceManager.GetString("lblRegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме.
        /// </summary>
        public static string lblRememberMe {
            get {
                return ResourceManager.GetString("lblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string lblRightsReserved {
            get {
                return ResourceManager.GetString("lblRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход със профил в социалните мрежи.
        /// </summary>
        public static string lblSocial {
            get {
                return ResourceManager.GetString("lblSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Silvex Shop.
        /// </summary>
        public static string lblTheSilvexShop {
            get {
                return ResourceManager.GetString("lblTheSilvexShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име/Email.
        /// </summary>
        public static string lblUsernameEmail {
            get {
                return ResourceManager.GetString("lblUsernameEmail", resourceCulture);
            }
        }
    }
}
