//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFishShop.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OnlineFishShopResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnlineFishShopResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineFishShop.Common.Resources.OnlineFishShopResources", typeof(OnlineFishShopResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;The Silvex Shop&lt;/b&gt; е онлайн магазин с отношение и фокус &lt;br&gt; върху морските дарове - риба,рибни продукти и премиум аксесоари. &lt;br&gt;  През изминалите 9 години ние се превърнахме в предпочитания &lt;br&gt; български рибен магазин, &lt;br&gt; като през първите 6 месеца на 2017 фодина обслужихме над 20 000 поръчки..
        /// </summary>
        public static string lblAboutText {
            get {
                return ResourceManager.GetString("lblAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влезте в профила си.
        /// </summary>
        public static string lblAccountLogin {
            get {
                return ResourceManager.GetString("lblAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Административен панел.
        /// </summary>
        public static string lblAdminPanel {
            get {
                return ResourceManager.GetString("lblAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банков превод.
        /// </summary>
        public static string lblBankPayment {
            get {
                return ResourceManager.GetString("lblBankPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        public static string lblBlog {
            get {
                return ResourceManager.GetString("lblBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наложен платеж.
        /// </summary>
        public static string lblCashOnDelivery {
            get {
                return ResourceManager.GetString("lblCashOnDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждаване на парола.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Адрес: &lt;/b&gt; &lt;br&gt; гр. София 1784 &lt;br&gt; бул. &quot;Цариградско шосе&quot; 159.
        /// </summary>
        public static string lblContactAdress {
            get {
                return ResourceManager.GetString("lblContactAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;E-mail: &lt;/b&gt; &lt;br&gt; info@fish-international.com &lt;br&gt; sales@silvex-seafoods.com.
        /// </summary>
        public static string lblContactEmails {
            get {
                return ResourceManager.GetString("lblContactEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string lblContatcs {
            get {
                return ResourceManager.GetString("lblContatcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright - 2019.
        /// </summary>
        public static string lblCopyright {
            get {
                return ResourceManager.GetString("lblCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на нов потребител.
        /// </summary>
        public static string lblCreateNewAccount {
            get {
                return ResourceManager.GetString("lblCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еmail адрес.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Факс: &lt;/b&gt; &lt;br&gt; 02/9798243.
        /// </summary>
        public static string lblFaxNumber {
            get {
                return ResourceManager.GetString("lblFaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола?.
        /// </summary>
        public static string lblForgotPassword {
            get {
                return ResourceManager.GetString("lblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;GSM: &lt;/b&gt; &lt;br&gt; 0899908571.
        /// </summary>
        public static string lblGSM {
            get {
                return ResourceManager.GetString("lblGSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте,.
        /// </summary>
        public static string lblHello {
            get {
                return ResourceManager.GetString("lblHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разнообразие от продукти &lt;br&gt; Гарантирано качество &lt;br&gt; Бърза доставка.
        /// </summary>
        public static string lblHomeDescription {
            get {
                return ResourceManager.GetString("lblHomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление на категории.
        /// </summary>
        public static string lblManageCategories {
            get {
                return ResourceManager.GetString("lblManageCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне, премахване, редактиране.
        /// </summary>
        public static string lblManageDescr {
            get {
                return ResourceManager.GetString("lblManageDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление на продукти.
        /// </summary>
        public static string lblManageProducts {
            get {
                return ResourceManager.GetString("lblManageProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление на потребители.
        /// </summary>
        public static string lblManageUsers {
            get {
                return ResourceManager.GetString("lblManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съобщение.
        /// </summary>
        public static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Методи за плащане:.
        /// </summary>
        public static string lblPaymentMethods {
            get {
                return ResourceManager.GetString("lblPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Телефон: &lt;/b&gt; &lt;br&gt; 02/9798243.
        /// </summary>
        public static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукти.
        /// </summary>
        public static string lblProducts {
            get {
                return ResourceManager.GetString("lblProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string lblRegister {
            get {
                return ResourceManager.GetString("lblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистриране на нов потребител.
        /// </summary>
        public static string lblRegisterNew {
            get {
                return ResourceManager.GetString("lblRegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме.
        /// </summary>
        public static string lblRememberMe {
            get {
                return ResourceManager.GetString("lblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string lblRightsReserved {
            get {
                return ResourceManager.GetString("lblRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string lblSend {
            get {
                return ResourceManager.GetString("lblSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход със профил в социалните мрежи.
        /// </summary>
        public static string lblSocial {
            get {
                return ResourceManager.GetString("lblSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия за поръчка и доставка:.
        /// </summary>
        public static string lblTermsAndConditions {
            get {
                return ResourceManager.GetString("lblTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимална стойност на поръчка: &lt;b&gt; 20.00лв. &lt;/b&gt; &lt;br&gt; За поръчки до 13:00ч. (Пон-Пет): &lt;br&gt; доставка същия ден от 13:00ч. до 18:00ч. &lt;br&gt; За поръчки след 13:00ч. или в почивен ден: &lt;br&gt; доставка на следващ работен ден от 11:00ч. до 18:00ч..
        /// </summary>
        public static string lblTermsAndConditionsText {
            get {
                return ResourceManager.GetString("lblTermsAndConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Silvex Shop.
        /// </summary>
        public static string lblTheSilvexShop {
            get {
                return ResourceManager.GetString("lblTheSilvexShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име/Email.
        /// </summary>
        public static string lblUsernameEmail {
            get {
                return ResourceManager.GetString("lblUsernameEmail", resourceCulture);
            }
        }
    }
}
